Repository BbiBbo8/moo-sa-hi, pull requests merged in 2025-04, with the labels that each got.

#44 Feature/#37 tabs 컴포넌트
  package.json
  pnpm-lock.yaml
  src/app/(pages)/profile/page.tsx
  src/components/.gitkeep
  src/components/ProfileTabs.tsx
  src/components/ui/Tabs.tsx
Labels: Feature

#48 Style: 일상 커뮤니티 페이지 레이아웃
  package.json
  pnpm-lock.yaml
  public/sampleScreenshot.png
  public/shorty.jpeg
  public/ugly.jpeg
  public/고양이.jpeg
  public/우리캐릭터2 1 (1).png
  src/app/(pages)/community-daily/page.tsx
  src/components/ui/avatar.tsx
  src/components/ui/card.tsx
  src/components/ui/carousel.tsx
  src/components/ui/tabs.tsx
Labels: Style

#51 Feature/#9 tab navigation bar 컴포넌트 생성
  src/app/layout.tsx
  src/components/TabNavigateBar.tsx
  src/constants/PATH.ts
Labels: Feature

#68 Feature/#67 map component
  package.json
  pnpm-lock.yaml
  src/app/(pages)/map/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/components/layout/TabNavigateBar.tsx
  src/components/map/InputSearch.tsx
  src/components/map/MapComponent.tsx
  src/components/map/MapGeolocation.tsx
  src/components/map/MapGeolocationComponent.tsx
  src/components/map/ShelterList.tsx
  src/components/ui/command.tsx
  src/components/ui/dialog.tsx
  src/hooks/useMapGeolocation.ts
  src/store/useMapStore.ts
Labels: Feature

#69 fetch : server.ts파일 생성과 supabase 타입 연동 & 로그인 로직 수정
  database.types.ts
  package.json
  pnpm-lock.yaml
  src/app/(pages)/auth/callback/page.tsx
  src/app/(pages)/auth/nickname/page.tsx
  src/app/(pages)/community-daily/page.tsx
  src/components/auth/LogoutButton.tsx
  src/components/auth/NicknameForm.tsx
  src/components/auth/SocialLoginButtons.tsx
  src/supabase/client.ts
  src/supabase/server.ts
Labels: Feature

#72 Docs: 이슈 템플릿 수정
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: 문서

#73 Docs: 버그 템플릿 수정
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: 문서

#74 Docs: PR 템플릿 수정
  .github/pull_request_template.md
Labels: 문서

#80 Feature/#71 map preview: 내 위치 기반 지도 미리보기 표시
  src/components/landing/MapPreview.tsx
Labels: Feature

#83 Feature/#63 post create supabase
  package.json
  pnpm-lock.yaml
  src/api/fetchSheltersApi.ts
  src/app/(pages)/post-create/page.tsx
  src/components/community/PostCreateEdit.tsx
  src/components/community/form/DailyForm.tsx
  src/components/community/form/ShelterForm.tsx
  src/components/post/PostCreateEdit.tsx
  src/components/ui/daily.tsx
  src/components/ui/form.tsx
  src/components/ui/label.tsx
  src/components/ui/shelter.tsx
  src/components/ui/textarea.tsx
  src/components/ui/toast.tsx
  src/components/ui/toaster.tsx
  src/components/ui/use-toast.ts
Labels: Refactor

#86 hotfix: 패키지 병합 오류 수정 #85
  pnpm-lock.yaml
Labels: 🚨hotfix

#90 Feat: supabase데이터 가져오기
  database.types.ts
  public/sampleScreenshot.png
  public/shorty.jpeg
  public/ugly.jpeg
  public/고양이.jpeg
  public/우리캐릭터2 1 (1).png
  src/app/(pages)/community-daily/page.tsx
  src/app/layout.tsx
  src/components/community/CommunityTabs.tsx
  src/components/community/PostCard.tsx
  src/components/ui/drawer.tsx
  src/providers/providers.tsx
  src/supabase/getCommuniy.ts
Labels: Feature

#99 Feature/#88 shelter api map
  src/app/(pages)/map/page.tsx
  src/components/map/InputSearch.tsx
  src/components/map/MapComponent.tsx
  src/components/map/MapPageComponent.tsx
  src/hooks/useShelterMapEffect.ts
  src/store/useMapStore.ts
Labels: Feature

#121 Refactor/#88 shelter list
  src/app/(pages)/map/page.tsx
  src/app/api/fetchSheltersApi.ts
  src/components/landing/MapPreview.tsx
  src/components/map/InputSearch.tsx
  src/components/map/MainMap.tsx
  src/components/map/MapClient.tsx
  src/components/map/MapGeolocation.tsx
  src/components/map/ShelterDrawer.tsx
  src/components/map/ShelterList.tsx
  src/components/map/UserGeolocationMap.tsx
  src/hooks/shelter/useShelters.ts
  src/hooks/useShelterMapEffect.ts
  src/store/useShelterStore.ts
Labels: Refactor

#117 Refactor/#116 기능별 컴포넌트화와 코드 개선
  package.json
  pnpm-lock.yaml
  public/shorty.jpeg
  src/app/(pages)/community-daily/[id]/page.tsx
  src/app/(pages)/community-daily/page.tsx
  src/app/(pages)/community-shelter/[id]/page.tsx
  src/app/(pages)/community-shelter/page.tsx
  src/app/(pages)/sign-in/page.tsx
  src/components/auth/ProfileImageInput.tsx
  src/components/community/CommunityTabs.tsx
  src/components/community/DailyPost.tsx
  src/components/community/ShelterPost.tsx
  src/components/community/ShelterPostDetail.tsx
  src/types/.gitkeep
  src/types/communityPost.ts
  src/utils/ShelterPostDetailsQuery.tsx
  src/utils/getImageSrc.ts
Labels: Refactor

#130 Feature/#126 대피소 게시글 페이지에 지도 렌더링
  database.types.ts
  src/app/(pages)/community-daily/[id]/page.tsx
  src/app/(pages)/community-daily/page.tsx
  src/app/(pages)/community-shelter/[id]/page.tsx
  src/app/(pages)/community-shelter/page.tsx
  src/components/community/DailyDetailPost.tsx
  src/components/community/DailyPost.tsx
  src/components/community/ShelterDetailPost.tsx
  src/components/community/ShelterPost.tsx
  src/utils/shelterPostDetailsQuery.tsx
Labels: Feature

#138 feat: 대피소 리스트 지도 맵 마커 필터링 기능 만들기
  next.config.ts
  src/components/map/MainMap.tsx
  src/components/map/ShelterDrawer.tsx
  src/components/map/ShelterList.tsx
  src/hooks/shelter/useShelters.ts
  src/store/useMapStore.ts
  src/store/useMarkerStore.ts
Labels: Feature

#141 [대피소디테일] 대피소정보 렌더링 및 추가 개선 완료
  src/app/(pages)/map/[id]/page.tsx
  src/app/api/fetchSheltersApi.ts
  src/components/map/ShelterExtraFeature.tsx
  src/types/shelter.ts
Labels: Feature, Refactor

#149 [대피소디테일] 외부 지도 연결 및 장소공유 기능 구현 성공
  src/app/(pages)/map/[id]/page.tsx
  src/components/detail/ShelterExtraFeature.tsx
  src/components/map/ShelterExtraFeature.tsx
Labels: Feature

#153 Feature/#127 일상/대피소 커뮤니티 페이지 버튼들 구현
  src/app/(pages)/community-daily/page.tsx
  src/app/(pages)/community-shelter/page.tsx
  src/components/community/DailyDetailPost.tsx
  src/components/community/PostCreateFloatingBtn.tsx
  src/components/community/ShelterDetailPost.tsx
  src/hooks/community/useDailyPostDetailQuery.ts
Labels: Feature

#156 [랜딩페이지]재난 알림 배너 구현 성공
  src/app/api/fetchDisasterAlert.ts
  src/components/landing/AlertBanner.tsx
  src/types/disaster.ts
Labels: Feature, Style

#159 Feat/#145 marker label list link
  package.json
  pnpm-lock.yaml
  src/app/(pages)/map/[id]/page.tsx
  src/components/map/MainMap.tsx
  src/components/map/ShelterList.tsx
Labels: Feature

#163 [랜딩페이지] NewsCard 컴포넌트 추가 및 페이지에 통합
  next.config.ts
  public/icons/gps.svg
  src/app/page.tsx
  src/components/landing/NewsCard.tsx
Labels: Feature

#168 랜딩페이지 디자인시안대로 수정
  src/app/page.tsx
  src/components/landing/AlertBanner.tsx
  src/components/landing/BannerSection.tsx
  src/components/landing/MapPreview.tsx
  src/components/landing/NewsCard.tsx
  src/components/layout/Header.tsx
  src/components/map/UserGeolocationMap.tsx
Labels: Feature, Style, Refactor

#174 Feature/#165 커뮤니티 게시글 검색 기능
  src/app/(pages)/community-daily/page.tsx
  src/app/(pages)/community-shelter/page.tsx
  src/components/community/CommunityHeader.tsx
  src/components/community/SearchBarToggle.tsx
Labels: Feature, Style, Refactor

#176 [랜딩페이지] 전체 수정 완료
  public/icons/chevron-down-solid.svg
  public/icons/megaphone.svg
  public/landing/banner1.svg
  public/landing/banner2.svg
  public/landing/banner3.svg
  public/landing/banner4.svg
  public/landing/landing.svg
  src/app/page.tsx
  src/components/landing/AlertBanner.tsx
  src/components/landing/BannerSection.tsx
  src/components/landing/MapPreview.tsx
  src/components/landing/NewsCard.tsx
  src/components/landing/SectionDivider.tsx
Labels: Feature, Style, Refactor

#178 Feat/#173 marker list focus
  src/components/map/MainMap.tsx
  src/components/map/ShelterDrawer.tsx
  src/components/map/ShelterList.tsx
  src/store/useMarkerStore.ts
Labels: Feature, Refactor

#186 Style/#177 일상 & 대피소 레이아웃 수정
  database.types.ts
  public/icons/PencilSimple.svg
  public/icons/Property 1=Disabled.svg
  public/icons/bullhorn-solid 1.svg
  public/icons/thumbs-up-solid.svg
  src/app/(pages)/community-daily/page.tsx
  src/app/(pages)/community-shelter/page.tsx
  src/components/community/CommunityHeader.tsx
  src/components/community/DailyPost.tsx
  src/components/community/PostCreateFloatingBtn.tsx
  src/components/community/SearchBarToggle.tsx
  src/components/community/ShelterPost.tsx
  src/supabase/getCommuniy.ts
  src/types/communityPost.ts
Labels: Style

#193 [hotfix] 빌드 오류 수정 및 게시글 상세 페이지 디자인 수정
  src/app/(pages)/community-daily/page.tsx
  src/app/(pages)/community-shelter/page.tsx
  src/components/community/DailyPost.tsx
  src/components/community/ShelterDetailPost.tsx
  src/components/community/ShelterPost.tsx
  src/components/community/detail/DailyDetailPost.tsx
  src/components/community/detail/PostButtons.tsx
  src/components/community/detail/ShelterDetailPost.tsx
  src/utils/getImageSrc.ts
Labels: Style, Refactor

#196 style: 컴포넌트 UI 개선 및 카카오 맵 기능 추가
  public/icons/crosshairs-solid.png
  public/icons/minus-solid.png
  public/icons/plus-solid.png
  src/components/map/CrosshairButton.tsx
  src/components/map/InputSearch.tsx
  src/components/map/MainMap.tsx
  src/components/map/MapClient.tsx
  src/components/map/ShelterDrawer.tsx
  src/components/map/ShelterList.tsx
  src/components/map/ZoomControl.tsx
  src/store/useMapStore.ts
Labels: Feature, Style

#200 배포후 소셜로그인 테스트 코드 수정
  src/components/auth/SocialLoginButtons.tsx
Labels: 🚨hotfix

#204 Feat/#199 shelter list
  src/components/map/CrosshairButton.tsx
  src/components/map/ShelterDrawer.tsx
  src/components/map/ShelterList.tsx
  src/components/map/ZoomControl.tsx
  src/hooks/useDistance.ts
  src/hooks/useOnClickOutside.ts
  src/types/shelter.ts
Labels: Feature, Style

#211 Feat/#199 shelter list
  src/components/map/CrosshairButton.tsx
  src/components/map/InputSearch.tsx
  src/components/map/MainMap.tsx
  src/components/map/ShelterDrawer.tsx
  src/components/map/ShelterList.tsx
  src/components/map/ZoomControl.tsx
Labels: Style

#209 style: 게시글 작성 페이지 디자인 반영 및 수정
  public/icons/postcreate/chevron-down-solid.svg
  public/icons/postcreate/chevron-left-solid1.svg
  public/icons/postcreate/image-solid.svg
  src/app/(pages)/post-create/page.tsx
  src/components/community/PostCreateEdit.tsx
  src/components/community/form/DailyForm.tsx
  src/components/community/form/ShelterForm.tsx
  src/components/ui/BackButton.tsx
  src/components/ui/PostTypeDropdown.tsx
Labels: Style

#214 지도 페이지 스크롤 문제 해결 및 메타데이터 수정
  README.md
  public/icons/postcreate/chevron-down-solid.svg
  public/icons/postcreate/chevron-left-solid1.svg
  public/icons/postcreate/image-solid.svg
  src/app/(pages)/community-daily/page.tsx
  src/app/(pages)/community-shelter/page.tsx
  src/app/(pages)/post-create/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/components/community/PostCreateEdit.tsx
  src/components/community/form/DailyForm.tsx
  src/components/community/form/ShelterForm.tsx
  src/components/layout/TabNavigateBar.tsx
  src/components/map/CrosshairButton.tsx
  src/components/map/InputSearch.tsx
  src/components/map/MainMap.tsx
  src/components/map/ShelterDrawer.tsx
  src/components/map/ShelterList.tsx
  src/components/map/ZoomControl.tsx
  src/components/profile/ProfileCard.tsx
  src/components/ui/BackButton.tsx
  src/components/ui/PostTypeDropdown.tsx
Labels: 문서, Refactor

#221 Fix: 특정 버튼 클릭 시 로그인 여부에 따라 로그인 드로워가 열리도록 구현
  public/icons/shelter-detail/circle-info-solid.svg
  public/icons/shelter-detail/clock-solid.svg
  public/icons/shelter-detail/flag-solid.svg
  public/icons/shelter-detail/location-dot-solid.svg
  public/icons/shelter-detail/phone-solid.svg
  public/icons/shelter-detail/user-group-solid.svg
  src/app/(pages)/map/[id]/page.tsx
  src/app/(pages)/sign-in/page.tsx
  src/components/auth/SigninDrawer.tsx
  src/components/community/PostCreateFloatingBtn.tsx
  src/components/community/detail/DailyPostButtons.tsx
  src/components/community/detail/ShelterPostButton.tsx
  src/components/community/form/CommentForm.tsx
  src/components/detail/DetailMap.tsx
  src/components/detail/ShelterExtraFeature.tsx
Labels: Feature

#224 지도 페이지 버튼 및 드로어 수정
  next.config.ts
  public/icons/map/List Open.svg
  src/components/map/CrosshairButton.tsx
  src/components/map/ShelterDrawer.tsx
  src/components/map/ZoomControl.tsx
Labels: Feature, Style, Refactor

#233 refactor: 일상 글 등록 오류 고침 및 붐빔 탭 삭제
  src/components/community/PostCreateEdit.tsx
  src/components/community/form/DailyForm.tsx
  src/components/community/form/ShelterForm.tsx
Labels: Refactor

#236 refactor: 코드 간단 수정 #235
  src/components/community/PostCreateEdit.tsx
Labels: Refactor

#239 Refactor: 일부 기능 리팩토링
  src/app/(pages)/community-daily/page.tsx
  src/app/(pages)/community-shelter/page.tsx
  src/app/api/fetchSheltersApi.ts
  src/components/auth/SocialLoginButtons.tsx
  src/components/profile/ProfileEditPop.tsx
Labels: Feature, Style, Refactor

#242 hotfix: ScrollLocker 컴포넌트 제거 및 관련 스타일 삭제
  src/app/globals.css
  src/components/common/ScrollLocker.tsx
  src/components/map/MapClient.tsx
Labels: 🚨hotfix

#245 refactor: 사진 입력 구현, 일상 게시글 오류 수정, 스타일 수정 #234
  database.types.ts
  src/components/community/PostCreateEdit.tsx
  src/components/community/form/ImageDropzone.tsx
  src/components/community/form/ShelterForm.tsx
  src/components/ui/BackButton.tsx
Labels: Refactor

#247 Style/#230 지도 페이지 스타일 적용
  package.json
  pnpm-lock.yaml
  public/icons/crosshairs-solid.png
  public/icons/map/List-Open.svg
  public/icons/map/bars-solid.svg
  public/icons/map/crosshairs-solid.svg
  public/icons/map/map-location-dot-solid.png
  public/icons/map/minus-solid.svg
  public/icons/map/plus-solid.svg
  src/components/map/CrosshairButton.tsx
  src/components/map/InputSearch.tsx
  src/components/map/MainMap.tsx
  src/components/map/MapClient.tsx
  src/components/map/ShelterDrawer.tsx
  src/components/map/ShelterList.tsx
  src/components/map/ZoomControl.tsx
  src/components/ui/drawer.tsx
  src/components/ui/scroll-area.tsx
Labels: Style

#253 신고하기 버튼 구현
  database.types.ts
  src/components/community/detail/DailyDetailPost.tsx
  src/components/community/detail/DailyPostButtons.tsx
  src/components/community/detail/ShelterDetailPost.tsx
  src/components/community/detail/ShelterPostButton.tsx
  src/components/report/ReportButton.tsx
  src/components/report/ReportModal.tsx
  src/types/reports.ts
Labels: 문서, Feature, Style, Refactor

#256 hotfix:불필요한 디버깅 코드제거 및 에러처리 추가
  src/app/(pages)/community-daily/page.tsx
  src/components/community/detail/DailyDetailPost.tsx
  src/components/community/detail/ShelterDetailPost.tsx
  src/store/useShelterStore.ts
  src/supabase/imgBucket.ts
  src/supabase/server.ts
Labels: 🚨hotfix

#258 feat: 로그인 유지 구현 및 시안에 맞는 UI수정 #252
  middleware.ts
  src/components/community/PostCreateEdit.tsx
  src/components/community/form/DailyForm.tsx
  src/components/community/form/ShelterForm.tsx
Labels: Feature

#259 #251 대피소 리스트 리팩토링
  package.json
  pnpm-lock.yaml
  public/icons/map/chevron-down-solid.svg
  src/components/map/MainMap.tsx
  src/components/map/ShelterDrawer.tsx
  src/components/map/ShelterList.tsx
  src/components/ui/dropdown-menu.tsx
  src/store/useMapStore.ts
  src/store/useMarkerStore.ts
Labels: Feature, Style, Refactor

#271 style: 미들웨어 사용, 시안대로 반응형
  src/components/community/PostCreateEdit.tsx
Labels: Style

#274 실시간 댓글 알림 기능
  database.types.ts
  pnpm-lock.yaml
  public/icons/alarm.svg
  public/icons/alarm1.svg
  src/app/layout.tsx
  src/components/layout/Header.tsx
  src/components/layout/NotificationButton.tsx
  src/components/notifications/NotificationDropdown.tsx
  src/hooks/comment/useCommentMutation.ts
  src/hooks/useNotificationSubscription.ts
  src/types/notification.ts
  tsconfig.json
Labels: ⚠️ 버그, 문서, Feature, Style, Refactor

#278 랜딩페이지 전체 디자인 수정 및 댓글 최신순 나열
  public/icons/chevron-down-solid.svg
  public/icons/chevron-up-solid.svg
  public/landing/survey_banner.svg
  src/app/page.tsx
  src/components/community/CommentList.tsx
  src/components/landing/AlertBanner.tsx
  src/components/landing/BannerSection.tsx
  src/components/landing/Footer.tsx
  src/components/landing/MapPreview.tsx
  src/components/landing/NewsCard.tsx
Labels: 문서, Feature, Style, Refactor

#284 style: 검색창 전체 채우기
  src/components/map/InputSearch.tsx
  src/components/map/MapClient.tsx
  src/components/map/ShelterDrawer.tsx
Labels: Style

#285 지도 페이지 전체적 성능 개선 및 오류 수정
  package.json
  pnpm-lock.yaml
  src/components/map/MainMap.tsx
Labels: Feature, Refactor

#304 Refactor: Next/Image svg 사용 방식 변경
  src/components/map/CrosshairButton.tsx
  src/components/map/ShelterDrawer.tsx
  src/components/map/ZoomControl.tsx
Labels: Style, Refactor

#305 전체적인 리팩토링 작업
  package.json
  pnpm-lock.yaml
  public/icons/auth/google.svg
  public/icons/auth/kakao.svg
  public/icons/shelter-detail/copy-solid.svg
  public/icons/shelter-detail/share-nodes-solid 2.svg
  public/icons/shelter-detail/share-solid.svg
  public/typos/logo.svg
  src/app/(pages)/auth/callback/page.tsx
  src/app/(pages)/auth/nickname/page.tsx
  src/app/api/signout/route.ts
  src/components/auth/LogoutButton.tsx
  src/components/auth/SigninDrawer.tsx
  src/components/auth/SocialLoginButtons.tsx
  src/components/detail/ShelterExtraFeature.tsx
  src/components/landing/AlertBanner.tsx
  src/components/layout/Header.tsx
  src/components/map/ShelterDrawer.tsx
Labels: 문서, Feature, Style, Refactor

#309 Refactor: 랜딩페이지 이미지 경로 변경
  src/app/page.tsx
  src/components/landing/AlertBanner.tsx
  src/components/landing/BannerSection.tsx
  src/components/landing/MapPreview.tsx
Labels: Style, Refactor

#311 [카드뉴스] 연합뉴스 api로 실시간 뉴스카드 및 뉴스페이지 구현
  src/app/(pages)/map/[id]/page.tsx
  src/app/(pages)/news/[id]/page.tsx
  src/app/action/fetchDisasterAlert.ts
  src/app/action/fetchNewsApi.ts
  src/app/action/fetchSheltersApi.ts
  src/components/landing/AlertBanner.tsx
  src/components/landing/NewsCard.tsx
  src/hooks/shelter/useShelters.ts
  src/store/useShelterStore.ts
  src/types/news.ts
Labels: 문서, Feature, Style

#316 Style: 지도 페이지 부분 문제 수정
  public/icons/map/circle-xmark-solid.svg
  public/icons/map/magnifying-glass-solid.svg
  src/components/map/InputSearch.tsx
  src/components/map/MainMap.tsx
  src/components/map/ShelterDrawer.tsx
Labels: Style

#319 Fix:지도 & 대피소 페이지 레이아웃 수정과 디자인 변수 활용
  src/app/(pages)/map/[id]/page.tsx
  src/components/community/PostCreateFloatingBtn.tsx
  src/components/community/SearchBarToggle.tsx
  src/components/community/ShelterPost.tsx
  src/components/community/detail/DailyPostButtons.tsx
  src/components/community/detail/ShelterDetailPost.tsx
  src/components/community/detail/ShelterPostButton.tsx
  src/components/community/detail/banner.tsx
  src/components/detail/DetailMap.tsx
  src/components/landing/BannerSection.tsx
  src/components/landing/MapPreview.tsx
  src/components/map/ShelterDrawer.tsx
  src/components/map/ShelterList.tsx
  src/components/profile/BlankPost.tsx
  src/components/ui/BackButton.tsx
  src/components/ui/PostTypeDropdown.tsx
Labels: Style, Refactor
